experiment:
  data_config:
    strategy: fixed
    dataloader: VisualLoader
    dataset_path: ../data/{0}/trainingset.tsv
    train_path: ../data/{0}/trainingset.tsv
    validation_path: ../data/{0}/validationset.tsv
    test_path: ../data/{0}/testset.tsv
    side_information:
      visual_features: ../data/{0}/original/cnn_features_vgg19_fc2.npy #../data/{0}/original/cnn_features_resnet50_avg_pool/
      item_mapping: ../data/{0}/visual_feats.tsv
  dataset: amazon_baby
  top_k: 10
  evaluation:
    #cutoffs: [10, 100]
    simple_metrics: [nDCG] #[Precision, HR, F1, MRR, MAP, ItemCoverage, Gini, EFD, EPC, ACLT, APLT, ARP]
    relevance_threshold: 1
    paired_ttest: True
  gpu: 0
  models:
    BPRMF_batch:
      meta:
        hyper_opt_alg: grid
        validation_rate: 10
        verbose: True
        save_weights: True
        save_recs: False
        validation_metric: nDCG
        restore: -1
      lr: [0.0001, 0.001, 0.01]
      epochs: 100
      batch_size: 64
      factors: [32, 64, 128]
      l_w: [0.00001, 0.001, 0]
      l_b: 0
    VBPR:
      meta:
        hyper_opt_alg: grid
        validation_rate: 10
        verbose: True
        save_weights: True
        save: False
        validation_metric: nDCG
        restore: -1
      lr: [0.0001, 0.001, 0.01]
      epochs: 100
      factors: [32, 64, 128]
      factors_d: 20
      batch_size: 64
      batch_eval: 256
      l_w: [0.00001, 0.001, 0]
      l_b: 0
      l_e: [0.00001, 0.001, 0]
    AMF:
      meta:
        hyper_opt_alg: grid
        validation_rate: 10
        verbose: True
        save_weights: True
        save: False
        validation_metric: nDCG
        restore: -1
      epochs: 100
      batch_size: 64
      factors:  [32, 64, 128] #[quniform, 50, 100, 1]
      lr: [0.0001, 0.001, 0.01] #[loguniform, -2, -1]
      l_w: [0.00001, 0.001, 0] #0.0001
      l_b: 0 #0.0001
      eps:  0.2  #[uniform, 0.1, 0.5] # Magnitude of the Perturbation
      l_adv: 1 # Adversarial Regularization Parameters
      adversarial_epochs: 50 #[quniform, 4, 8, 1] # Number of final epochs to be run [APR starts from (epochs - adversarial_epochs) epoch]
    AMR:
      meta:
        hyper_opt_alg: grid
        validation_rate: 10
        verbose: True
        save_weights: True
        save: False
        validation_metric: nDCG
        restore: -1
      epochs: 100
      batch_size: 64
      factors: [32, 64, 128]
      factors_d: 20
      lr: [0.0001, 0.001, 0.01] #0.001
      l_w: [0.00001, 0.001, 0]  #0.1
      l_b: 0.001
      l_e: [0.00001, 0.001, 0]  #0.1
      eps: 0.2
      l_adv: 1  #0.001
      adversarial_epochs: 50