experiment:
  dataset: movielens_1m
  data_config:
    strategy: dataset
    dataset_path: ../data/Yelp_min/Yelp_checkins_del_tab.csv #../data/AmazonOffice/ratings_Office_Products_del_tab.csv   #../data/AmazonOffice/ratings_Office_Products_del_tab.csv   #../data/movielens_1m/dataset.tsv # '../data/Foursq/dataset_ubicomp2013_checkins_deli_tab.csv'  #../data/movielens_1m/dataset.tsv #../data/Epinions/ratings_data_deli_tab.csv   #../data/AmazonDigMusic/ratings_Digital_Music_deli_tab.csv #../data/Epinions/ratings_data_deli_tab.csv  #../data/AmazonDigMusic/ratings_Digital_Music_deli_tab.csv #../data/movielens_1m/dataset.tsv # ../data/AmazonDigMusic/ratings_Digital_Music.csv   #../data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 20
  evaluation:
    cutoffs: [5, 20]
    simple_metrics: [HR]
    relevance_threshold: 1
#  gpu: -1
  models:
    BPRMF:
      meta:
        hyper_opt_alg: grid
      factors: [64]   #[4, 8, 16, 32, 64]  #[4, 8, 16, 32, 64, 128]
      epochs: 100     #1000, 200
      lr: [0.01, 0.02, 0.05]
      ga: [1, 1.2, 1.3, 1.6, 2.4, 3.2, 4, 5, 6]

#experiment:
#  dataset: movielens_100k
#  data_config:
#    strategy: dataset #fixed #train_path:test_path:
#    dataset_path:  ../data/movielens_1m/dataset.tsv #../data/AmazonDigMusic/ratings_Digital_Music.csv  #../data/movielens_100k/u.data  #../data/movielens_1m/dataset.tsv
#  splitting:
#    test_splitting:
#        strategy: random_subsampling
#        test_ratio: 0.2
#   # validation_splitting:
#   #      strategy: random_cross_validation
#   #      test_ratio: 0.25
#   #      folds: 4
#  top_k: [10]
#  evaluation:
#    cutoffs: [10]
#    simple_metrics: [nDCG]
#    relevance_threshold: 4
#  models:
#    BPRMF:
#      meta:
#        hyper_max_evals: 144
#        hyper_opt_alg: grid
#      factors: [4, 8, 16, 32, 64, 128 ]  #[4, 8, 16, 32, 64, 128]
#      epochs: 5
#      lr: [ 0.001, 0.005, 0.01, 0.02 ]
#      ga: [ 0.6, 1, 1.6, 1.8, 2.4, 3.2 ]

