experiment:
  dataset: movielens_100k
  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_100k/u.data  #../data/movielens_100k/u.data #../data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 50
  evaluation:
    cutoffs: 50
    simple_metrics: [HR, nDCG, EFD, ACLT, APLT]
    paired_ttest: True
    wilcoxon_test: True
  gpu: 1
  models:
    AMF:
      meta:
        save_recs: False
        hyper_max_evals: 5
        hyper_opt_alg: tpe
      epochs: 10
      batch_size: 64 #256
      factors: 50 #[quniform, 50, 100, 1]
      lr: [loguniform, -2, -1]
      l_w: 0.0001
      l_b: 0.0001
      eps: [uniform, 0.1, 0.5] # Magnitude of the Perturbation
      l_adv: 1 # Adversarial Regularization Parameters
      adversarial_epochs: [quniform, 4, 8, 1] # Number of final epochs to be run [APR starts from (epochs - adversarial_epochs) epoch]

