experiment:
  dataset: movielens_100k
  data_config:
    strategy: dataset #fixed #train_path:test_path:
    dataset_path: ../data/movielens_100k/u.data  #../data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
   # validation_splitting:
   #      strategy: random_cross_validation
   #      test_ratio: 0.25
   #      folds: 4
  top_k: 10
  evaluation:
    simple_metrics: [nDCG]
    paired_ttest: True
    wilcoxon_test: True
  models:
    AMF:
      meta:
        save_recs: False
        hyper_max_evals: 5
        hyper_opt_alg: tpe
      epochs: 100
      batch_size: 256
      factors: [50, 80]   #[quniform, 50, 100, 1]
      lr: [ loguniform, -2, -1 ]
      l_w: 0.0001    # Eq (1) reg term
      l_b: 0.0001
      eps: [ uniform, 0.1, 0.5 ] # Magnitude of the Perturbation
      l_adv: 1 # Adversarial Regularization Parameters
      adversarial_epochs: [50] #50 from the end [ quniform, 4, 8, 1 ] # Number of final epochs to be run [APR starts from (epochs - adversarial_epochs) epoch]


      #  gpu: -1
#  models:
#    BPRMF:
#      meta:
#        validation_rate: 1
#        save_recs: True
#        save_weights: True
        #hyper_max_evals: 24 #168
        #hyper_opt_alg: grid
#      factors: 4  #8, 16]  #[4, 8, 16, 32, 64, 128]
#      epochs: 3
#      lr: 0.005  #, #0.005, 0.01]
#      ga: 1 #[0.6 0.8 1 1.6 1.8 2.4 3.2]
